/*
 Copyright (c) 2003-2017, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","de-ch",{title:"Barrierefreiheitinformationen",contents:"Hilfeinhalt. Um den Dialog zu schliessen die Taste ESC dr?cken.",legend:[{name:"Allgemein",items:[{name:"Editorwerkzeugleiste",legend:"Dr?cken Sie ${toolbarFocus} auf der Symbolleiste. Gehen Sie zur n?chsten oder vorherigen Symbolleistengruppe mit TAB und SHIFT+TAB. Gehen Sie zur n?chsten oder vorherigen Symbolleiste auf die Schaltfl?che mit dem RECHTS- oder LINKS-Pfeil. Dr?cken Sie die Leertaste oder Eingabetaste, um die Schaltfl?che in der Symbolleiste aktivieren."},
{name:"Editordialog",legend:"Inside a dialog, press TAB to navigate to the next dialog element, press SHIFT+TAB to move to the previous dialog element, press ENTER to submit the dialog, press ESC to cancel the dialog. When a dialog has multiple tabs, the tab list can be reached either with ALT+F10 or with TAB as part of the dialog tabbing order. With tab list focused, move to the next and previous tab with RIGHT and LEFT ARROW, respectively."},{name:"Editor-Kontextmen?",legend:"D?rcken Sie ${contextMenu} oder die Anwendungstaste um das Kontextmen? zu ?ffnen. Man kann die Pfeiltasten zum Wechsel benutzen. Mit der Leertaste oder der Enter-Taste kann man den Men?punkt aufrufen. Schliessen Sie das Kontextmen? mit der ESC-Taste."},
{name:"Editor-Listenbox",legend:"Innerhalb einer Listenbox kann man mit der TAB-Taste oder den Pfeilrunter-Taste den n?chsten Men?eintrag w?hlen. Mit der SHIFT+TAB Tastenkombination oder der Pfeilhoch-Taste gelangt man zum vorherigen Men?punkt. Mit der Leertaste oder Enter kann man den Men?punkt ausw?hlen. Dr?cken Sie ESC zum Verlassen des Men?s."},{name:"Editor-Elementpfadleiste",legend:"Dr?cken Sie ${elementsPathFocus} um sich durch die Pfadleiste zu bewegen. Um zum n?chsten Element zu gelangen dr?cken Sie TAB oder die Pfeilrechts-Taste. Zum vorherigen Element gelangen Sie mit der SHIFT+TAB oder der Pfeillinks-Taste. Dr?cken Sie die Leertaste oder Enter um das Element auszuw?hlen."}]},
{name:"Befehle",items:[{name:"R?ckg?ngig-Befehl",legend:"Dr?cken Sie ${undo}"},{name:"Wiederherstellen-Befehl",legend:"Dr?cken Sie ${redo}"},{name:"Fettschrift-Befehl",legend:"Dr?cken Sie ${bold}"},{name:"Kursiv-Befehl",legend:"Dr?cken Sie ${italic}"},{name:"Unterstreichen-Befehl",legend:"Dr?cken Sie ${underline}"},{name:"Link-Befehl",legend:"Dr?cken Sie ${link}"},{name:"Werkzeugleiste einklappen-Befehl",legend:"Dr?cken Sie ${toolbarCollapse}"},{name:"Zugang bisheriger Fokussierung Raumbefehl ",legend:"Dr?cken Sie ${accessPreviousSpace}  auf den am n?chsten nicht erreichbar Fokus-Abstand vor die Einf?gemarke zugreifen: zwei benachbarte HR-Elemente. Wiederholen Sie die Tastenkombination um entfernte Fokusr?ume zu erreichen. "},
{name:"Zugang n?chster Schwerpunkt Raumbefehl ",legend:"Dr?cken Sie $ { accessNextSpace }, um den n?chsten unerreichbar Fokus Leerzeichen nach dem Cursor zum Beispiel auf: zwei benachbarten HR Elemente. Wiederholen Sie die Tastenkombination zum fernen Fokus Bereiche zu erreichen. "},{name:"Eingabehilfen",legend:"Dr?cken Sie ${a11yHelp}"}]}],tab:"Tab",pause:"Pause",capslock:"Feststell",escape:"Escape",pageUp:"Bild auf",pageDown:"Bild ab",leftArrow:"Linke Pfeiltaste",upArrow:"Obere Pfeiltaste",rightArrow:"Rechte Pfeiltaste",
downArrow:"Untere Pfeiltaste",insert:"Einf?gen",leftWindowKey:"Linke Windowstaste",rightWindowKey:"Rechte Windowstaste",selectKey:"Taste ausw?hlen",numpad0:"Ziffernblock 0",numpad1:"Ziffernblock 1",numpad2:"Ziffernblock 2",numpad3:"Ziffernblock 3",numpad4:"Ziffernblock 4",numpad5:"Ziffernblock 5",numpad6:"Ziffernblock 6",numpad7:"Ziffernblock 7",numpad8:"Ziffernblock 8",numpad9:"Ziffernblock 9",multiply:"Multiplizieren",add:"Addieren",subtract:"Subtrahieren",decimalPoint:"Punkt",divide:"Dividieren",
f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Ziffernblock feststellen",scrollLock:"Rollen",semiColon:"Semikolon",equalSign:"Gleichheitszeichen",comma:"Komma",dash:"Bindestrich",period:"Punkt",forwardSlash:"Schr?gstrich",graveAccent:"Gravis",openBracket:"?ffnende eckige Klammer",backSlash:"R?ckw?rtsgewandter Schr?gstrich",closeBracket:"Schliessende eckige Klammer",singleQuote:"Einfaches Anf?hrungszeichen"});