/*
 Copyright (c) 2003-2017, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","oc",{euro:"Simb?l ?uro",lsquo:"Vergueta simpla dobrenta",rsquo:"Vergueta simpla tampanta",ldquo:"Vergueta dobla dobrenta",rdquo:"Vergueta dobla tampanta",ndash:"Jonhent semi-quadratin",mdash:"Jonhent quadratin",iexcl:"Punt d'exclamacion inversat",cent:"Simb?l cent",pound:"Simb?l Liura sterling",curren:"Simb?l monetari",yen:"Simb?l i?n",brvbar:"Barra verticala separada",sect:"Signe de seccion",uml:"Tr?ma",copy:"Simb?l Copyright",ordf:"Indicador ordinal femenin",
laquo:"Vergueta francesa dobrenta",not:"Croquet de negacion",reg:"Simb?l de marca depausada",macr:"Macron",deg:"Simb?l gra",sup2:"Exponent 2",sup3:"Exponent 3",acute:"Accent agut",micro:"Simb?l micro",para:"Simb?l p? de m?sca",middot:"Punt median",cedil:"Cedilha",sup1:"Exponent 1",ordm:"Indicador ordenal masculin",raquo:"Vergueta francesa tampanta",frac14:"Fraccion un quart",frac12:"Fraccion un mi?g",frac34:"Fraccion tres quarts",iquest:"Punt d'interrogacion inversat",Agrave:"A accent gr?u majuscula",
Aacute:"A accent agut majuscula",Acirc:"A accent circonfl?xe majuscula",Atilde:"A caron majuscula",Auml:"A tr?ma majuscula",Aring:"A redond majuscula",AElig:"Ligatura ? majuscula",Ccedil:"C c?dille majuscula",Egrave:"E accent gr?u majuscula",Eacute:"E accent agut majuscula",Ecirc:"E accent circonfl?xe majuscula",Euml:"E tr?ma majuscula",Igrave:"I accent gr?u majuscula",Iacute:"I accent agut majuscula",Icirc:"I accent circonfl?xe majuscula",Iuml:"I tr?ma majuscula",ETH:"Letra majuscula islandaise ED",
Ntilde:"N caron majuscula",Ograve:"O accent gr?u majuscula",Oacute:"O accent agut majuscula",Ocirc:"O accent circonfl?xe majuscula",Otilde:"O caron majuscula",Ouml:"O tr?ma majuscula",times:"Simb?l de multiplicacion",Oslash:"O raiat majuscula",Ugrave:"U accent gr?u majuscula",Uacute:"U accent agut majuscula",Ucirc:"U accent circonfl?xe majuscula",Uuml:"U tr?ma majuscula",Yacute:"Y accent agut majuscula",THORN:"Letra islandesa thorn majuscula",szlig:"Letra minuscula alemanda S dur",agrave:"A accent gr?u minuscula",
aacute:"A accent agut minuscula",acirc:"A accent circonfl?xe minuscula",atilde:"A tilda minuscula",auml:"A tr?ma minuscula",aring:"A redond minuscula",aelig:"Ligatura ? minuscula",ccedil:"C c?dille minuscula",egrave:"E accent gr?u minuscula",eacute:"E accent agut minuscula",ecirc:"E accent circonfl?xe minuscula",euml:"E tr?ma minuscula",igrave:"I accent gr?u minuscula",iacute:"I accent agut minuscula",icirc:"I accent circonfl?xe minuscula",iuml:"i minuscula tr?ma",eth:"Letra minuscula islandaise ED",
ntilde:"N caron minuscula",ograve:"O minuscula accent gr?u",oacute:"O accent agut minuscula",ocirc:"O accent circonfl?xe minuscula",otilde:"O tilda minuscula",ouml:"O tr?ma minuscula",divide:"Simb?l de division",oslash:"O raiat minuscula",ugrave:"U accent gr?u minuscula",uacute:"U accent agut minuscula",ucirc:"U accent circonfl?xe minuscula",uuml:"U tr?ma minuscula",yacute:"Y accent agut minuscula",thorn:"Letra islandaise thorn minuscula",yuml:"Y tr?ma minuscula",OElig:"Ligatura ? majuscula",oelig:"Ligatura ? minuscula",
372:"W accent circonfl?xe majuscula",374:"Y accent circonfl?xe majuscula",373:"W accent circonfl?xe minuscula",375:"Y accent circonfl?xe minuscula",sbquo:"Vergueta simpla tampanta inferior",8219:"Vergueta-virgula superior culbut?",bdquo:"Vergueta-virgula double inferior",hellip:"Punts de suspension",trade:"Simb?l de marca comerciala",9658:"Sageta negra puntant cap a dreita",bull:"Gr?s punt median",rarr:"Sageta cap a dreita",rArr:"Sageta dobla cap a dreita",hArr:"Sageta dobla cap a esqu?rra",diams:"Lausange negre",
asymp:"Environ egal"});